### ISSUE TITLE
BE: finish setting up CI to run smooth

### ISSUE THREAD

**Issue by alexGrandolph** [PupTrainer/be_puptrainer#3]

**Comment by Josenecal** [comment]
## Resolution

We still want to run security checks before deployment, but this check will always fail because it will pick up on the fact that our implemented version of Rails is no longer supported. We don not find that it makes sense at this time to upgrade to a currently supported version of Rails, and so we will allow this check to fail, but we'll keep running it to ensure that's the ONLY reason it fails. 

### Further Development

- As part of this process, our team decided to drop linting requirements, at least as a first priority. This could be reinstated for better developer empathy 
- Because of the failing security check, we currently don't have Heroku set to wait for CI before auto-deployment. Because of this, there is the distinct possibility of pushing code to deployment that would have failed RSpec tests and could break functionality. The flow should be further developed in the future to allow for continuted security checks under some circumstances, while leaving RSpec tests to run concurrent to deployment, so any failed tests can prevent that process for happening.
